MSVC fixes
libofx/libofx pull request #47
Opened 2021-10-19 12:05 UTC by wrobelda

This is a bunch of fixes that allow to compile against MSVC, with an exception of the `getopt` that likely needs a more thorough discussion.

Originally provided by:
https://invent.kde.org/packaging/craft-blueprints-kde/-/tree/master/libs/libofx

References #46

2021-10-19 14:02 UTC, wrobelda commented
OK, so removing explicit `-lstdc++` breaks building on *nix, although to my knowledge this should be required at all if g++ was used.

2021-10-19 19:40 UTC, jralls commented
> OK, so removing explicit -lstdc++ breaks building on *nix, although to my knowledge this should be required at all if g++ was used.

I think you mean "shouldn't be required at all if g++ was used".

That's not quite right: It shouldn't be required at all if g++ is used *to link the program*. The program that's failing to link is ofx2qif and it's a C program so it gets linked with gcc.

The other piece of the puzzle is static linkage. With dynamic linkage only the symbols that the program needs are linked so a C program can use the libofx C API. With static linkage all of libofx's symbols need to be resolved and that requires the C++ standard library. Note that the current invocation `-lstdc++` would be broken on clang because by default it uses a different C++ std library, libc++.

The simplest fix for getting libofx to build is probably to rename ofx2qif.c to ofx2qif.cpp. You'll also need to qualify the OFX_account enum vaues, a pretty trivial change.

2021-10-19 20:09 UTC, wrobelda commented
> I think you mean "shouldn't be required at all if g++ was used".

Indeed.

> That's not quite right: It shouldn't be required at all if g++ is used to link the program. The program that's failing to link is ofx2qif and it's a C program so it gets linked with gcc.

That makes sense, frankly speaking I did not look too deeply into it.

> The simplest fix for getting libofx to build is probably to rename ofx2qif.c to ofx2qif.cpp.

The simplest fix on my end was simply only removing the `-lstdc++` usage when compiling with MSVC, but that's a rather dirty workaround. I'll look into it.

2021-10-20 11:26 UTC, wrobelda commented
> The other piece of the puzzle is static linkage. With dynamic linkage only the symbols that the program needs are linked so a C program can use the libofx C API. With static linkage all of libofx's symbols need to be resolved and that requires the C++ standard library. Note that the current invocation -lstdc++ would be broken on clang because by default it uses a different C++ std library, libc++.

I am battling with this right now. However, static linkage actually works fine on macOS with _clang_, without changing anything in Makefiles. On Linux, however, using gcc, it fails with unresolved symbols to STD. Any ideas?

2021-10-21 00:37 UTC, jralls commented
> I am battling with this right now. However, static linkage actually works fine on macOS with clang, without changing anything in Makefiles. 

It didn't when I tested it, using Xcode13 on macOS 11.6.

2021-10-21 12:57 UTC, wrobelda commented
> The simplest fix for getting libofx to build is probably to rename ofx2qif.c to ofx2qif.cpp. You'll also need to qualify the OFX_account enum vaues, a pretty trivial change.

OK, fixed and included in this branch. Haven't found any other issues on any platform.

2021-10-21 15:43 UTC, jralls commented
Except that you repeated your "Expllicit linking against libstdc++ should be required" mistake in the commit summary; in fact you're removing that explicit linkage. The commit summary should be something like "Ensure that static linkage of C++ standard library is automatic."

2021-10-21 15:54 UTC, wrobelda commented
> Except that you repeated your "Expllicit linking against libstdc++ should be required" mistake in the commit summary; in fact you're removing that explicit linkage. The commit summary should be something like "Ensure that static linkage of C++ standard library is automatic."

Indeed, my bad, forgot to push the reworded commit message. Updated per your suggestions.

2021-10-27 13:29 UTC, wrobelda commented
Is there anything else to be done here?

2021-10-27 15:17 UTC, benoitg commented
The point of ofx2qif being in C is to make sure the library works directly with c programs, especially that libofx.h remains entirely compatible with C.  It did detect problems several times in the past.

2021-10-27 23:14 UTC, jralls commented
> The point of ofx2qif being in C is to make sure the library works directly with c programs, especially that libofx.h remains entirely compatible with C. It did detect problems several times in the past.

And it has detected one now: It's incompatible with static linkage and the workaround works only with gcc.

2021-11-02 02:24 UTC, benoitg commented
Well, ok, but skipping building ofx2qif it at all on MSVC seems like less bad solution than turning ofx2qif into a C++ program and changing the comment to pretend it was meant as a C++ example in the first place.

2021-11-02 04:08 UTC, jralls commented
It's not just msvc, it's every compiler except gcc (or clang with the `-stdlib=libstdc++` compile option)when building static. There are two ways around it: Setting a config variable for the std c++ library flag to pass in or disable ofx2qif in a static build.

2021-11-02 16:41 UTC, benoitg commented
Haven't played with C/C++ build systems for a decade, so I can't really help, but i'm fine with either, just not turning ofx2qif into a C++ program.

2021-11-18 17:08 UTC, jralls commented
@wrobelda Does msvcrt have a way to statically link the C++ standard library?

2022-01-02 19:09 UTC, cstim requested changes
I'm not convinced of the lib/Makefile.am change with removing -lstd++ from LIBADD unconditionally. 

Apart from that change, I think everything else is ready to go in, yes.

In the Makefile.am, you could introduce a conditional so that only on non-windows, -lstdc++ continues to be added?

2022-01-02 21:43 UTC, jralls commented
@cstim If ofx2qif is made to compile with the C++ compiler, which this PR as it stands now does, then `-lstdc++` is unnecessary because the c++ compiler links the right C++ standard library. But @benoitg objects to that, insisting that `ofx2qif` be compiled with the C compiler to test that that works, but that builds only with gcc because other compilers either spell the C++ standard library name differently or in Microsoft's case don't appear to provide one at all. For compilers that do provide one it can be determined at configure time and put in a variable that's added to ofx2qif's AM_LDADD. ISTM the only recourse with MSVC is to disable static builds of ofx2qif.

2022-04-19 18:14 UTC, wrobelda commented
So, do we have any consensus on how to proceed here? I'd argue that having support for MSVC is valuable addition and worth the effort of getting this merged in.

2022-04-19 18:43 UTC, jralls commented
@wrobelda It occurs to me there's another way that might allow MSVC to compile statically: Instead of linking libofx at startup ofx2qif could `dlopen` it.

2022-06-29 11:24 UTC, wrobelda commented
@cstim @jralls I updated the PR and did the following:
– only the ofx2qif is linked against stdc++
– I made it configurable to disable building of all tools

So while it doesn't fix building of ofx2qif under Windows, it at least allows to successfully compile the library itself.

2022-06-29 21:06 UTC, cstim commented
Okay, to me it looks fine... although if I understood correctly, the tool "ofxdump" wasn't a problem at all, hence it wouldn't need to be disabled, right?

2022-06-29 21:07 UTC, cstim approved these changes

2022-06-29 21:13 UTC, wrobelda commented
> Okay, to me it looks fine... although if I understood correctly, the tool "ofxdump" wasn't a problem at all, hence it wouldn't need to be disabled, right?

Correct, but it just made more sense to add a switch to disable building all the tools together. This will also be useful for vcpkg usage, where end-user tools are expected not to be compiled at all.

2022-06-29 21:37 UTC, cstim commented
Just for easier reading in the git history I'd keep the _WIN32 commit as one commit, but squash the other commits into one more commit. Care to do the squash on your branch, so that I can rebase this directly?

2022-06-29 21:46 UTC, wrobelda commented
> Just for easier reading in the git history I'd keep the _WIN32 commit as one commit, but squash the other commits into one more commit. Care to do the squash on your branch, so that I can rebase this directly?

I grouped them into three separate ones, hope they make sense?

2022-06-30 12:11 UTC, merged

2022-09-09 18:43 UTC, landryb commented
fwiw, using clang 13 on OpenBSD, the build of `ofx2qif` now fails with missing `stdc++`:

```
/usr/bin/libtool  --tag=CC   --mode=link cc  -DIN_LIBOFX -fvisibility=hidden -O2 -pipe  -L/usr/local/lib -o ofx2qif ofx2qif.o ../lib/libofx.la -lstdc++                                                              
warning: could not find a stdc++ library                                                                                                                                                                             
Link error: stdc++ not found!   
```

removing `-lstdc++` from `ofx2qif/Makefile.in` allows me to build 0.10.7.