Fix getopt usage under MSVC
libofx/libofx pull request #50
Opened 2021-10-19 16:25 UTC by wrobelda

MSVC does not have an implementation of getopt. KDE folks, however, have patched libofx a while ago to workaround it. 

Originally from:
https://invent.kde.org/packaging/craft-blueprints-kde/-/tree/master/libs/libofx

Note that the distributable package provides a different version of `ofxdump\cmdline.c`, presumably regenerated by `gengetopt`, which requires additional patching:

```
diff --git a/ofxdump/cmdline.c b/ofxdump/cmdline.c
index 98a41c3..5bf5121 100644
--- a/ofxdump/cmdline.c
+++ b/ofxdump/cmdline.c
@@ -21,7 +21,7 @@
 #define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
 #endif
 
-#include <getopt.h>
+#include "getopt.h"
 
 #include "cmdline.h"
 
@@ -395,7 +395,6 @@ int update_arg(void *field, char **orig_field,
   const char *val = value;
   int found;
   char **string_field;
-  FIX_UNUSED (field);
 
   stop_char = 0;
   found = 0;
@@ -498,8 +497,6 @@ cmdline_parser_internal (
 
   optarg = 0;
   optind = 0;
-  opterr = params->print_errors;
-  optopt = '?';
 
   while (1)
     {
```

2021-10-21 13:15 UTC, wrobelda commented
Oddly, this works fine when compiled from the command line on macOS, but fails under vcpkg. I'd imagine there are better ways to sort it out.

```
ld: warning: directory not found for option '-L/Users/cromo/Documents/Sourcecode/vcpkg/installed/arm64-osx/debug/lib/manual-link/'
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt1.c:71:19: warning: declaration of 'struct option' will not be visible outside of this function [-Wvisibility]
     const struct option *long_options;
                  ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt1.c:74:10: error: implicit declaration of function '_getopt_internal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  return _getopt_internal (argc, argv, options, long_options, opt_index, 0);
         ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:511:19: warning: declaration of 'struct option' will not be visible outside of this function [-Wvisibility]
     const struct option *longopts;
                  ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:653:14: warning: incompatible pointer types assigning to 'const struct option *' from 'const struct option *' [-Wincompatible-pointer-types]
      for (p = longopts, option_index = 0; p->name; p++, option_index++)
             ^ ~~~~~~~~
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:653:45: error: incomplete definition of type 'struct option'
      for (p = longopts, option_index = 0; p->name; p++, option_index++)
                                           ~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:653:54: error: arithmetic on a pointer to an incomplete type 'const struct option'
      for (p = longopts, option_index = 0; p->name; p++, option_index++)
                                                    ~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: .././../src/0.10.3-f53874554e/ofxdump/../lib/getopt1.c:87:19: warning: declaration of 'struct option' will not be visible outside of this function [-Wvisibility]
     const struct option *long_options;
                  ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt1.c:90:10: error: implicit declaration of function '_getopt_internal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  return _getopt_internal (argc, argv, options, long_options, opt_index, 1);
         ^
note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:654:17:2 warnings and 2 errors generated.
 error: incomplete definition of type 'struct option'
        if (!strncmp (p->name, nextchar, nameend - nextchar))
                      ~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:657:30: error: incomplete definition of type 'struct option'
                == (unsigned int) strlen (p->name))
                                          ~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:672:17: error: incomplete definition of type 'struct option'
                     || pfound->has_arg != p->has_arg
                        ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:672:31: error: incomplete definition of type 'struct option'
                     || pfound->has_arg != p->has_arg
                                           ~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:673:17: error: incomplete definition of type 'struct option'
                     || pfound->flag != p->flag
                        ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:673:28: error: incomplete definition of type 'struct option'
                     || pfound->flag != p->flag
                                        ~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:674:17: error: incomplete definition of type 'struct option'
                     || pfound->val != p->val)
                        ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:674:27: error: incomplete definition of type 'struct option'
                     || pfound->val != p->val)
                                       ~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
make[2]: *** [getopt1.o] Error 1
make[2]: *** Waiting for unfinished jobs....
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:698:18: error: incomplete definition of type 'struct option'
              if (pfound->has_arg)
                  ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:708:21: error: incomplete definition of type 'struct option'
                                 argv[0], pfound->name);
                                          ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:713:42: error: incomplete definition of type 'struct option'
                                 argv[0], argv[optind - 1][0], pfound->name);
                                                               ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:718:20: error: incomplete definition of type 'struct option'
                  optopt = pfound->val;
                           ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:722:19: error: incomplete definition of type 'struct option'
          else if (pfound->has_arg == 1)
                   ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:733:20: error: incomplete definition of type 'struct option'
                  optopt = pfound->val;
                           ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: forward declaration of 'struct option'
      const struct option *p;
                   ^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:740:14: error: incomplete definition of type 'struct option'
          if (pfound->flag)
              ~~~~~~^
.././../src/0.10.3-f53874554e/ofxdump/../lib/getopt.c:641:20: note: for [...]

2021-10-21 15:50 UTC, jralls commented
Maybe you don't have `-Werror` in $CFLAGS when building from the command line.

2021-10-21 15:58 UTC, wrobelda commented
> Maybe you don't have `-Werror` in $CFLAGS when building from the command line.

Tried `-Werror`, but it's not that. Must be some other switch or a combination thereof.

2021-10-21 16:36 UTC, jralls commented
If I try to build this branch after `git clean -fdx && ./autogen.sh` in srcdir I can't complete configure:
checking for gengetopt... no
configure: error: *** Gengetopt is not found, and generated files (cmdline.c) are missing (probably because you checked out from git).  You need to install gengetopt ***

Which is correct: I haven't installed gengetopt because the point of the branch is to build without it. But cmdline.c and cmdline.h are *generated files* created by running gengetopt.h. You can't bypass that in a git build--which this is--and you can't blindly apply the KDE patches because they're made against a distribution tarball that contains the generated files, not the git repository.

2021-10-21 18:04 UTC, jralls commented
Meanwhile, in a prefix that does have gengetopt installed and after fixing #52, I get the same set of errors, though with the files in the order you specified in Makefile.am rather than what you copied into your earlier comment.

On Debian Sid, getopt and getopt1 compile OK but cmdline still fails with
```
gcc -DHAVE_CONFIG_H -I. -I../../libofx/ofxdump -I..  -I../inc '-DCMDLINE_PARSER_PACKAGE="ofxdump"'   -DIN_LIBOFX -fvisibility=hidden -g -O2 -MT cmdline.o -MD -MP -MF .deps/cmdline.Tpo -c -o cmdline.o cmdline.c
cmdline.c: In function ‘cmdline_parser_internal’:
cmdline.c:499:3: error: ‘optarg’ undeclared (first use in this function)
  499 |   optarg = 0;
      |   ^~~~~~
cmdline.c:499:3: note: each undeclared identifier is reported only once for each function it appears in
cmdline.c:500:3: error: ‘optind’ undeclared (first use in this function)
  500 |   optind = 0;
      |   ^~~~~~
cmdline.c:501:3: error: ‘opterr’ undeclared (first use in this function)
  501 |   opterr = params->print_errors;
      |   ^~~~~~
cmdline.c:502:3: error: ‘optopt’ undeclared (first use in this function)
  502 |   optopt = '?';
      |   ^~~~~~
cmdline.c:508:28: error: array type has incomplete element type ‘struct option’
  508 |       static struct option long_options[] = {
      |                            ^~~~~~~~~~~~
cmdline.c:522:11: warning: implicit declaration of function ‘getopt_long’ [-Wimplicit-function-declaration]
  522 |       c = getopt_long (argc, argv, "hVf:", long_options, &option_index);
      |           ^~~~~~~~~~~
```

2021-10-21 20:25 UTC, jralls commented
```
diff --git a/ofxdump/Makefile.am b/ofxdump/Makefile.am
index 3d4794e..407a4b9 100644
--- a/ofxdump/Makefile.am
+++ b/ofxdump/Makefile.am
@@ -1,8 +1,12 @@
 bin_PROGRAMS = ofxdump
 ofxdump_LDADD = $(top_builddir)/lib/libofx.la
-ofxdump_SOURCES = cmdline.h cmdline.c ofxdump.cpp $(top_builddir)/lib/getopt.c $(top_builddir)/lib/getopt1.c
+ofxdump_SOURCES = cmdline.h cmdline.c ofxdump.cpp
 dist_man_MANS = ofxdump.1

+if NO_GETOPTLONG
+ofxdump_SOURCES += $(top_builddir)/lib/getopt.c $(top_builddir)/lib/getopt1.c
+endif
+
 AM_CPPFLAGS = \
        -I${top_builddir}/inc \
        '-DCMDLINE_PARSER_PACKAGE="ofxdump"'
diff --git a/ofxdump/getopt.h b/ofxdump/getopt.h
index 70ded8e..090b3a1 100644
--- a/ofxdump/getopt.h
+++ b/ofxdump/getopt.h
@@ -1 +1,5 @@
+#ifndef HAVE_GETOPT_LONG
 #include "../lib/getopt.h"
+#else
+#include_next <getopt.h>
+#endif
```
Fixes the build with non-MSVC compilers for OSes that provide getopt either in libc or libgnugetopt. Note, however, that your addition of lib/getopt.h is problematic because in the event that getopt isn't supported configure should symlink lib/gnugetopt.h to lib/getopt.h.  libgnugetopt declares `optarg`, `opterr`, and `optopt` and your getopt.h doesn't, which is what caused cmdline.c to not compile.

2021-10-21 21:17 UTC, wrobelda commented
>  Note, however, that your addition of lib/getopt.h is problematic because in the event that getopt isn't supported configure should symlink lib/gnugetopt.h to lib/getopt.h. libgnugetopt declares optarg, opterr, and optopt and your getopt.h doesn't, which is what caused cmdline.c to not compile.

Yes, very much aware of this – this is what the diff I pasted in my first comment does, i.e. it removes the references to optarg and opterr. And please mind that it isn't my code – in fact, it was part of the very hackish KDE's patch that it's been using for at least 8 years now.

For what it's worth, I was able to use that hackish patch in vcpkg for Windows builds, but ideally all the required fixes should be upstreamed.

2022-01-02 19:05 UTC, cstim requested changes
The newly introduced header may be fine, but the other changes I've commented on do not make sense to me in this form.

2022-01-02 19:05 UTC, cstim commented on ofxdump/getopt.h
> +#include "../lib/getopt.h"
I don't think this file is needed or should be added - it rather confuses stuff. If the header is included from within the ofxdump directory, please use a relative include at source code level.

2022-01-02 19:05 UTC, cstim commented on ofxdump/Makefile.am
> +ofxdump_SOURCES = cmdline.h cmdline.c ofxdump.cpp $(top_builddir)/lib/getopt.c $(top_builddir)/lib/getopt1.c
This change does not make sense to me - in this PR there is neither a file getopt.c introduced in builddir, nor one named getopt1.c.

2022-07-21 13:10 UTC, closed without merging