Ignore SGML parser character error because the char is accepted fine (#60)
libofx/libofx pull request #64
Opened 2022-07-18 20:38 UTC by cstim

This adds code to identify the SGML's parser error that is "thrown" when encountering a non-ascii character. We count those occurrences and subtract it from the final error count.

2022-07-18 21:17 UTC, jralls requested changes
Looks reasonable.

2022-07-18 21:17 UTC, jralls commented on lib/ofx_sgml.cpp
> +const std::string MESSAGE_NON_SGML_CHAR = "non SGML character";
`static const` to keep it out of the global namespace.

2022-07-18 21:17 UTC, jralls commented on lib/ofx_sgml.cpp
> +        message = message + "ignored parser error:";
Rather than "ignored parser error: " how about "ignored character error: "?

2022-07-19 17:56 UTC, cstim commented on lib/ofx_sgml.cpp
> +const std::string MESSAGE_NON_SGML_CHAR = "non SGML character";
ok

2022-07-19 17:56 UTC, cstim commented on lib/ofx_sgml.cpp
> +        message = message + "ignored parser error:";
ok

2022-07-22 17:26 UTC, clawoflight commented
I can confirm this resolves my issue, both with ofxdump and in skrooge (using LD_PRELOAD).
Thank you!

2022-07-23 19:54 UTC, merged